version: '3'
services:
  api:
    image: cognyte-challenge-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/event_manager
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=admin
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=event_manager
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
